function [obstacles, envInfo] = generateCSSCEnvironment2D(envType, opts)
%GENERATECSSCENVIRONMENT2D Generate randomized obstacle sets for 2D CSSC demos.
%
% Usage:
%   [obstacles, envInfo] = generateCSSCEnvironment2D('randomCircles', opts);
%   [obstacles, envInfo] = generateCSSCEnvironment2D('randomRects', opts);
%   [obstacles, envInfo] = generateCSSCEnvironment2D('randomMixed', opts);
%
% Key opts:
%   common        : bounds, startPt, goalPt, seed, minGap, maxTry,
%                   keepoutStart, keepoutGoal
%   randomCircles : nObs, radiusRange
%   randomRects   : nObs, halfSizeXRange, halfSizeYRange, yawRange
%   randomMixed   : nCircle, nRect, radiusRange, halfSizeXRange,
%                   halfSizeYRange, yawRange
%
% Structured benchmark scenes are generated by
% generateCSSCStructuredEnvironment2D.

    if nargin < 1 || isempty(envType)
        envType = 'randomMixed';
    end
    if nargin < 2 || isempty(opts)
        opts = struct();
    end

    opts = setCommonDefaults(opts);
    if ~isempty(opts.seed)
        rng(opts.seed);
    end

    envKey = lower(char(envType));

    switch envKey
        case {'randomcircles','random_circles','circles'}
            [obstacles, envInfo] = makeRandomCircles(opts);

        case {'randomrects','random_rects','rects','rectangles'}
            [obstacles, envInfo] = makeRandomRects(opts);

        case {'randommixed','random_mixed','mixed'}
            [obstacles, envInfo] = makeRandomMixed(opts);

        otherwise
            error('Unknown randomized environment type: %s', char(envType));
    end

    envInfo.type = envKey;
    envInfo.category = 'randomized';
    envInfo.bounds = opts.bounds;
    envInfo.seed = opts.seed;
    envInfo.startPt = opts.startPt;
    envInfo.goalPt = opts.goalPt;
    envInfo.numObstacles = numel(obstacles);
end

function opts = setCommonDefaults(opts)
    if ~isfield(opts, 'bounds'); opts.bounds = [0, 1; -0.4, 0.4]; end
    if ~isfield(opts, 'startPt'); opts.startPt = [0.05, 0.0]; end
    if ~isfield(opts, 'goalPt'); opts.goalPt = [0.95, 0.0]; end
    if ~isfield(opts, 'seed'); opts.seed = 1; end
    if ~isfield(opts, 'maxTry'); opts.maxTry = 3000; end
    if ~isfield(opts, 'minGap'); opts.minGap = 0.025; end
    if ~isfield(opts, 'keepoutStart'); opts.keepoutStart = 0.08; end
    if ~isfield(opts, 'keepoutGoal'); opts.keepoutGoal = 0.08; end

    opts.startPt = opts.startPt(:).';
    opts.goalPt = opts.goalPt(:).';
end

function [obstacles, envInfo] = makeRandomCircles(opts)
    nObs = getOpt(opts, 'nObs', getOpt(opts, 'numObstacles', 10));
    radiusRange = getOpt(opts, 'radiusRange', [0.025, 0.055]);

    obstacles = emptyObstacleArray();
    accepted = zeros(0, 3);
    rejected = 0;
    tries = 0;

    while numel(obstacles) < nObs && tries < opts.maxTry
        tries = tries + 1;
        r = randRange(radiusRange);
        c = randomPointInBounds(opts.bounds, r);

        if isBlockedByKeepout(c, r, opts) || overlapsAccepted(c, r, accepted, opts.minGap)
            rejected = rejected + 1;
            continue;
        end

        obstacles(end+1,1) = obsCircle2D(c, r); %#ok<AGROW>
        accepted(end+1,:) = [c, r]; %#ok<AGROW>
    end

    envInfo = baseInfo(opts);
    envInfo.description = 'Random circular obstacles.';
    envInfo.requestedObstacles = nObs;
    envInfo.rejectedSamples = rejected;
    envInfo.tries = tries;
    envInfo.radiusRange = radiusRange;
end

function [obstacles, envInfo] = makeRandomRects(opts)
    nObs = getOpt(opts, 'nObs', getOpt(opts, 'numObstacles', 8));
    halfSizeXRange = getOpt(opts, 'halfSizeXRange', [0.025, 0.070]);
    halfSizeYRange = getOpt(opts, 'halfSizeYRange', [0.025, 0.080]);
    yawRange = getOpt(opts, 'yawRange', [-pi/4, pi/4]);

    obstacles = emptyObstacleArray();
    accepted = zeros(0, 3);
    rejected = 0;
    tries = 0;

    while numel(obstacles) < nObs && tries < opts.maxTry
        tries = tries + 1;
        halfSize = [randRange(halfSizeXRange), randRange(halfSizeYRange)];
        yaw = randRange(yawRange);
        boundRadius = norm(halfSize);
        c = randomPointInBounds(opts.bounds, boundRadius);

        if isBlockedByKeepout(c, boundRadius, opts) || overlapsAccepted(c, boundRadius, accepted, opts.minGap)
            rejected = rejected + 1;
            continue;
        end

        obstacles(end+1,1) = obsRect2D(c, halfSize, yaw); %#ok<AGROW>
        accepted(end+1,:) = [c, boundRadius]; %#ok<AGROW>
    end

    envInfo = baseInfo(opts);
    envInfo.description = 'Random rectangular obstacles.';
    envInfo.requestedObstacles = nObs;
    envInfo.rejectedSamples = rejected;
    envInfo.tries = tries;
    envInfo.halfSizeXRange = halfSizeXRange;
    envInfo.halfSizeYRange = halfSizeYRange;
    envInfo.yawRange = yawRange;
end

function [obstacles, envInfo] = makeRandomMixed(opts)
    nCircle = getOpt(opts, 'nCircle', 7);
    nRect = getOpt(opts, 'nRect', 6);
    radiusRange = getOpt(opts, 'radiusRange', [0.022, 0.050]);
    halfSizeXRange = getOpt(opts, 'halfSizeXRange', [0.025, 0.060]);
    halfSizeYRange = getOpt(opts, 'halfSizeYRange', [0.025, 0.075]);
    yawRange = getOpt(opts, 'yawRange', [-pi/4, pi/4]);

    obstacles = emptyObstacleArray();
    accepted = zeros(0, 3);
    rejected = 0;
    tries = 0;

    target = nCircle + nRect;
    nCircleMade = 0;
    nRectMade = 0;

    while numel(obstacles) < target && tries < opts.maxTry
        tries = tries + 1;
        makeCircle = nCircleMade < nCircle && ...
            (nRectMade >= nRect || rand < nCircle / max(1, target));

        if makeCircle
            r = randRange(radiusRange);
            c = randomPointInBounds(opts.bounds, r);
            boundRadius = r;

            if isBlockedByKeepout(c, boundRadius, opts) || overlapsAccepted(c, boundRadius, accepted, opts.minGap)
                rejected = rejected + 1;
                continue;
            end

            obstacles(end+1,1) = obsCircle2D(c, r); %#ok<AGROW>
            accepted(end+1,:) = [c, boundRadius]; %#ok<AGROW>
            nCircleMade = nCircleMade + 1;
        else
            halfSize = [randRange(halfSizeXRange), randRange(halfSizeYRange)];
            yaw = randRange(yawRange);
            boundRadius = norm(halfSize);
            c = randomPointInBounds(opts.bounds, boundRadius);

            if isBlockedByKeepout(c, boundRadius, opts) || overlapsAccepted(c, boundRadius, accepted, opts.minGap)
                rejected = rejected + 1;
                continue;
            end

            obstacles(end+1,1) = obsRect2D(c, halfSize, yaw); %#ok<AGROW>
            accepted(end+1,:) = [c, boundRadius]; %#ok<AGROW>
            nRectMade = nRectMade + 1;
        end
    end

    envInfo = baseInfo(opts);
    envInfo.description = 'Mixed random circular and rectangular obstacles.';
    envInfo.requestedCircles = nCircle;
    envInfo.requestedRects = nRect;
    envInfo.generatedCircles = nCircleMade;
    envInfo.generatedRects = nRectMade;
    envInfo.rejectedSamples = rejected;
    envInfo.tries = tries;
    envInfo.radiusRange = radiusRange;
    envInfo.halfSizeXRange = halfSizeXRange;
    envInfo.halfSizeYRange = halfSizeYRange;
    envInfo.yawRange = yawRange;
end

function tf = isBlockedByKeepout(c, r, opts)
    tf = norm(c - opts.startPt) <= opts.keepoutStart + r || ...
         norm(c - opts.goalPt) <= opts.keepoutGoal + r;
end

function tf = overlapsAccepted(c, r, accepted, minGap)
    tf = false;
    for i = 1:size(accepted, 1)
        if norm(c - accepted(i,1:2)) <= r + accepted(i,3) + minGap
            tf = true;
            return;
        end
    end
end

function p = randomPointInBounds(bounds, margin)
    x = bounds(1,1) + margin + rand * max(0, bounds(1,2) - bounds(1,1) - 2*margin);
    y = bounds(2,1) + margin + rand * max(0, bounds(2,2) - bounds(2,1) - 2*margin);
    p = [x, y];
end

function val = randRange(range)
    val = range(1) + rand * (range(2) - range(1));
end

function val = getOpt(opts, name, defaultVal)
    if isfield(opts, name)
        val = opts.(name);
    else
        val = defaultVal;
    end
end

function envInfo = baseInfo(opts)
    envInfo = struct();
    envInfo.bounds = opts.bounds;
    envInfo.seed = opts.seed;
    envInfo.startPt = opts.startPt;
    envInfo.goalPt = opts.goalPt;
end

function obstacles = emptyObstacleArray()
    obstacles = repmat(obsCircle2D([0, 0], 0), 0, 1);
end
