function opts = defaultSpRRT2DParams(opts)
%DEFAULTSPRRT2DPARAMS Fill defaults for Adaptive Sp-RRT-2D.
%
% nominalLinkCount records the six-link robot configuration but does not
% limit tree depth. maxSegmentCount limits the number of fixed-length
% leader-path segments generated by the reverse search.

    if nargin < 1 || isempty(opts)
        opts = struct();
    end

    if isfield(opts, 'nLinks') && ...
            ~isfield(opts, 'nominalLinkCount')
        opts.nominalLinkCount = opts.nLinks;
    end
    if isfield(opts, 'thetaLimits') && ...
            ~isfield(opts, 'thetaMax') && ~isempty(opts.thetaLimits)
        opts.thetaMax = max(opts.thetaLimits);
    end

    opts = setDefault(opts, 'L', 0.15);
    opts = setDefault(opts, 'nominalLinkCount', 6);
    opts = setDefault(opts, 'maxSegmentCount', 12);
    opts = setDefault(opts, 'thetaMax', 40*pi/180);
    opts = setDefault(opts, 'bounds', [0, 1; -0.4, 0.4]);
    opts = setDefault(opts, 'seed', 1);
    opts = setDefault(opts, 'maxIter', 4000);
    opts = setDefault(opts, 'maxTimeSec', inf);
    opts = setDefault(opts, 'entranceBias', 0.05);
    opts = setDefault(opts, 'collisionResolution', 0.003);
    opts = setDefault(opts, 'inflateRadius', 0.0);
    opts = setDefault(opts, 'lengthTolerance', 1e-8);
    opts = setDefault(opts, 'angleTolerance', 1e-10);
    opts = setDefault(opts, 'reachabilityTolerance', 1e-9);
    opts = setDefault(opts, 'duplicateTolerance', 1e-10);
    opts = setDefault(opts, 'terminalDirectionEnabled', false);
    opts = setDefault(opts, 'storeTree', false);
    opts = setDefault(opts, 'verbose', false);
    opts = setDefault(opts, 'emitWarnings', true);

    % Compatibility metadata. Search logic uses L, thetaMax, and
    % maxSegmentCount directly.
    opts.nLinks = opts.nominalLinkCount;
    opts.linkLengths = opts.L * ones(1, opts.nominalLinkCount);
    opts.thetaLimits = opts.thetaMax * ones(1, opts.maxSegmentCount);

    if ~isfield(opts, 'pathOptimization') || isempty(opts.pathOptimization)
        opts.pathOptimization = struct();
    end
    opts.pathOptimization = setDefault( ...
        opts.pathOptimization, 'enable', true);
    opts.pathOptimization = setDefault( ...
        opts.pathOptimization, 'mode', 'non-worsening-angle');
    opts.pathOptimization = setDefault( ...
        opts.pathOptimization, 'angleTolerance', opts.angleTolerance);
    opts.pathOptimization = setDefault( ...
        opts.pathOptimization, 'thetaMax', opts.thetaMax);
end

function s = setDefault(s, name, value)
    if ~isfield(s, name) || isempty(s.(name))
        s.(name) = value;
    end
end
