clear; clc; close all;

%% Demo: candidate structured benchmark scenarios
% Structured scene geometry is generated by src/environment.

try
    projectRoot = initCSSCProjectPath;
catch
    projectRoot = fileparts(fileparts(mfilename('fullpath')));
end

saveFigure = false;

common = struct();
common.bounds = [0, 1; -0.4, 0.4];
common.startPt = [0.05, 0.0];
common.goalPt = [0.95, 0.0];

sceneTypes = {'singleSlit', 'offsetDoubleSlit', 'fourRectSChannel', 'staggeredBaffles3'};
scenarioCells = cell(numel(sceneTypes), 1);

for i = 1:numel(sceneTypes)
    [obstacles, envInfo] = generateCSSCStructuredEnvironment2D(sceneTypes{i}, common);
    envInfo.obstacles = obstacles;
    scenarioCells{i} = envInfo;
end
scenarioSet = vertcat(scenarioCells{:});

fig = figure('Color','w', ...
    'Name','Structured CSSC benchmark candidates', ...
    'Position',[120 100 1100 760]);
tiledlayout(2, 2, 'Padding','compact', 'TileSpacing','compact');

for i = 1:numel(scenarioSet)
    sc = scenarioSet(i);
    nexttile;
    hold on; grid on; axis equal;
    title(sprintf('%d. %s', i, sc.name), 'Interpreter','none');
    xlabel('x'); ylabel('y');

    drawBounds(sc.bounds);
    drawObstacles(sc.obstacles);
    drawObstacleLabels(sc.obstacles, sc.obstacleLabels);
    plot([sc.startPt(1), sc.goalPt(1)], [sc.startPt(2), sc.goalPt(2)], ...
        'k--', 'LineWidth', 0.8, 'HandleVisibility','off');
    plot(sc.startPt(1), sc.startPt(2), 'go', ...
        'MarkerFaceColor','g', 'DisplayName','start');
    plot(sc.goalPt(1), sc.goalPt(2), 'rp', ...
        'MarkerFaceColor','r', 'DisplayName','goal');

    xlim(sc.bounds(1,:));
    ylim(sc.bounds(2,:));
end

fprintf('\n[structured scenario candidates]\n');
for i = 1:numel(scenarioSet)
    fprintf('%2d | %-22s | obstacles=%2d | %s\n', ...
        i, scenarioSet(i).id, numel(scenarioSet(i).obstacles), ...
        scenarioSet(i).description);
end
fprintf('\nUse scenarioSet(k).obstacles / startPt / goalPt / bounds after choosing cases.\n');

if saveFigure
    outDir = fullfile(projectRoot, 'results', 'tmp');
    if ~exist(outDir, 'dir'); mkdir(outDir); end
    outFile = fullfile(outDir, 'structured_scenario_candidates.png');
    exportgraphics(fig, outFile, 'Resolution', 220);
    fprintf('[saved] %s\n', outFile);
end

%% Drawing helpers

function drawBounds(bounds)
    x = bounds(1,:);
    y = bounds(2,:);
    plot([x(1), x(2), x(2), x(1), x(1)], ...
         [y(1), y(1), y(2), y(2), y(1)], ...
         'k-', 'LineWidth', 1.0, 'HandleVisibility','off');
end

function drawObstacles(obstacles)
    for i = 1:numel(obstacles)
        obs = obstacles(i);
        switch lower(obs.type)
            case 'circle'
                drawCircle(obs.center, obs.radius, [0.20 0.35 0.80], 1.25, '-');

            case {'rect','rectangle','box'}
                drawRect(obs.center, obs.halfSize, obs.yaw, [0.25 0.25 0.25], 1.25, '-');
        end
    end
end

function drawObstacleLabels(obstacles, labels)
    if isempty(labels)
        return;
    end

    nLabel = min(numel(obstacles), numel(labels));
    for i = 1:nLabel
        text(obstacles(i).center(1), obstacles(i).center(2), labels{i}, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontWeight','bold', ...
            'Color',[0.05 0.05 0.05], ...
            'HandleVisibility','off');
    end
end

function drawCircle(c, r, color, lw, style)
    th = linspace(0, 2*pi, 120);
    fill(c(1) + r*cos(th), c(2) + r*sin(th), color, ...
        'FaceAlpha',0.18, 'EdgeColor',color, 'LineWidth',lw, ...
        'LineStyle',style, 'HandleVisibility','off');
end

function drawRect(c, h, yaw, color, lw, style)
    R = [cos(yaw), -sin(yaw);
         sin(yaw),  cos(yaw)];

    pts = [
        -h(1), -h(2)
         h(1), -h(2)
         h(1),  h(2)
        -h(1),  h(2)
        -h(1), -h(2)
    ];

    pts = (R * pts.').' + c;
    fill(pts(:,1), pts(:,2), color, ...
        'FaceAlpha',0.18, 'EdgeColor',color, 'LineWidth',lw, ...
        'LineStyle',style, 'HandleVisibility','off');
end
